import { siteConfig } from '../consts/site';
import type { Post, Video } from './content';

/** Absolute URL for an OG image generated by src/pages/og/[...route].ts. */
export const ogImageUrl = (key: string) => `${siteConfig.url}/og/${key}.png`;

/** Absolute URL from a site-relative path. */
export const absoluteUrl = (path: string) => new URL(path, siteConfig.url).href;

export const youtubeThumbnail = (id: string, quality: 'hq' | 'maxres' = 'maxres') =>
  `https://i.ytimg.com/vi/${id}/${quality === 'maxres' ? 'maxresdefault' : 'hqdefault'}.jpg`;

export function personJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    name: siteConfig.name,
    url: siteConfig.url,
    jobTitle: siteConfig.jobTitle,
    description: siteConfig.description,
    email: `mailto:${siteConfig.email}`,
    knowsAbout: [...siteConfig.knowsAbout],
    sameAs: [siteConfig.social.github, siteConfig.social.linkedin, siteConfig.social.youtube],
  };
}

export function articleJsonLd(post: Post, canonical: string) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.data.title,
    description: post.data.description,
    datePublished: post.data.pubDate.toISOString(),
    dateModified: (post.data.updatedDate ?? post.data.pubDate).toISOString(),
    author: { '@type': 'Person', name: siteConfig.name, url: siteConfig.url },
    publisher: { '@type': 'Person', name: siteConfig.name, url: siteConfig.url },
    image: ogImageUrl(post.id),
    url: canonical,
    mainEntityOfPage: { '@type': 'WebPage', '@id': canonical },
    keywords: post.data.tags.join(', '),
    articleSection: post.data.category,
  };
}

export function breadcrumbJsonLd(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: absoluteUrl(item.url),
    })),
  };
}

export function videoJsonLd(video: Video) {
  return {
    '@context': 'https://schema.org',
    '@type': 'VideoObject',
    name: video.data.title,
    description: video.data.description,
    thumbnailUrl: [youtubeThumbnail(video.data.youtubeId)],
    uploadDate: video.data.publishedAt.toISOString(),
    contentUrl: `https://www.youtube.com/watch?v=${video.data.youtubeId}`,
    embedUrl: `https://www.youtube-nocookie.com/embed/${video.data.youtubeId}`,
    ...(video.data.duration ? { duration: video.data.duration } : {}),
  };
}
